### ISSUE TITLE
Change to run with config file

### ISSUE THREAD

**Issue by samvanderzwan** [Project-OMOTES/simulator-core#104]
Instead of hard coded values in app.py, we should use a config file.
Discussed on 18-04-2024
We decided to use toml since then we can add comment in.
Look to pydantic for loading and saving.
@lfse-slafleur will check for the libaries to use.

**Comment by lfse-slafleur** [comment]
An option that I have good experience with is: https://github.com/ProtixIT/dataclass-binder
@MichielTukker  @samvanderzwan

**Comment by MichielTukker** [comment]
Config parameters are passed via SimulationConfiguration object
