### ISSUE TITLE
BaseAsset add_temp_to_node_equation rename

### ISSUE THREAD

**Issue by vanmeerkerk** [Project-OMOTES/simulator-core#113]
add_temp_to_node_equation should be refactored to add_internal_energy_to_node_equation

**Comment by samvanderzwan** [comment]
**Story Points: 21**
  [See the discussion](https://action.parabol.co/meet/xkYjbldVjW/estimate/3) in Sprint Poker #​​3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
