### ISSUE TITLE
Create basic consumer class

### ISSUE THREAD

**Issue by samvanderzwan** [Project-OMOTES/simulator-core#13]

**Comment by vanmeerkerk** [comment]
How are we tracking the references to the pandapipes items in the consumer class? Pandapipes is index oriented not object oriented. @samvanderzwan @vanmeerkerk

**Comment by vanmeerkerk** [comment]
@octavianor  @samvanderzwan  did we figure out the "correct" way to implement the consumer (demand_cluster)?
