### ISSUE TITLE
Passing message back to user

### ISSUE THREAD

**Issue by samvanderzwan** [Project-OMOTES/simulator-core#142]
We need to pass the following back to the user:

- [x] message
- [x] percentage done
- [ ] estimated remaining calculation time  _`(Update 5-dec-2024:  Won't do for now)`_

@MichielTukker needs to define how we can pass messages back and in what format.

**Comment by MichielTukker** [comment]
This should currently be handled by the simulator-worker. 

- The messages are captured by the worker and passed to the front-end
- the progress is monitored via a callback,  I'll also add this to the ```simulation_manager```

**Comment by MichielTukker** [comment]
How often should we send progress back to the frontend?  

Easiest (code-wise)  is every timestep,  but that may be a bit much. 

@samvanderzwan  @lfse-slafleur   any opinions?

**Comment by MichielTukker** [comment]
We've implemented the logic in the simulation loop in simulator-core.  the method has an argument `max_number_messages` which limits the number of calls to the `progress_update_handler`.   It has a default value of 15 messages.   This was merged in #145  and  Project-OMOTES/simulator-worker#31

Calculating the remaining simulation time should be a job for the frontend I think?

**Comment by lfse-slafleur** [comment]
@MichielTukker Remaining simulation time is currently quite difficult to solve in general and is not a feature we are currently looking at. Unless we put it on the list of course ^^.

**Comment by MichielTukker** [comment]
I haven't seen any requests for this feature so far, and the backend currently doesn't provide any method for reporting the "time remaining".   Ill close this issue for now.

**Comment by MichielTukker** [comment]
done
