### ISSUE TITLE
JAVA_HOME error on computer without Java

### ISSUE THREAD

**Issue by vanmeerkerk** [Project-OMOTES/simulator-core#158]
A fresh install of the venv and running app.py results in a error. The PC does not have a Java installed and so JAVA_HOME is not findable.

**Comment by MichielTukker** [comment]
To resolve this,  we need to refactor the ates class and mappers.     Ates imports pyjnius at the root of the file,   mappers import ates a the root,  so as soon as the mappers are loaded/called,  it crashes because java is not installed.

**Comment by MichielTukker** [comment]
Closed by #216.  Because Pyjinius is only loaded when the Ates class is initialized,  pyjjnius does not have to be installed (unless you want to run a model with an Ates)
