### ISSUE TITLE
Refactor py_esdl_from_file to use Path and str

### ISSUE THREAD

**Issue by samvanderzwan** [Project-OMOTES/simulator-core#161]
Based on Pr #156 idea is to make esdl from file to be able to handle strings and path as input

**Comment by MichielTukker** [comment]
Revised description:   `omotes_simulator_core.infrastructure.utils.pyesdl_from_file()`  currently accepts str as input.  This function should be refactored such that it accepts both str and Path objects and handles both cases (checking if file exists & conversion for `pyesdl.EnergySystemHandler.load_file()`)

**Comment by vanmeerkerk** [comment]
It should accept a Path from the pathlib module. 

from pathlib import Path.

@AshrafAlmohagryDeltares
