### ISSUE TITLE
Create output conversion to database

### ISSUE THREAD

**Issue by samvanderzwan** [Project-OMOTES/simulator-core#23]

**Comment by MichielTukker** [comment]
Depends on the database structure  (waiting on Sebastiaan/Mark)

**Comment by MichielTukker** [comment]
Yes,  this has been implemented in simulator-worker: Project-OMOTES/simulator-worker@0ba3b92d08d46523bf0eda5c53d0194c6d2d2729   (release tag 0.0.4)
