### ISSUE TITLE
Create list of ESDL objects and their PandaPipes counterparts

### ISSUE THREAD

**Issue by MichielTukker** [Project-OMOTES/simulator-core#3]
Create list of ESDL objects and their PandaPipes counterparts

**Comment by samvanderzwan** [comment]
added it to:
([https://365tno.sharepoint.com/❌/r/teams/P060.55186/TeamDocuments/Team/Work/Backend/Simulator/asset_parameter.xlsx?d=wafd9b7c395a84a6c8f231924eedf4897&csf=1&web=1&e=CjOqWv](https://365tno.sharepoint.com/:x:/r/teams/P060.55186/TeamDocuments/Team/Work/Backend/Simulator/asset_parameter.xlsx?d=wafd9b7c395a84a6c8f231924eedf4897&csf=1&web=1&e=CjOqWv))

**Comment by samvanderzwan** [comment]
We are not using pp anrymore so issue closed
