### ISSUE TITLE
ProductionCluster can not handle negative production

### ISSUE THREAD

**Issue by vanmeerkerk** [Project-OMOTES/simulator-core#30]
Flow reversal over the current implementation of the production cluster (i.e., flow control valve and mass flow circulation pump) is not solvable.

**Comment by vanmeerkerk** [comment]
@samvanderzwan we need to decide if we want to support negative mass flow. Currently the code throws an exception, but the simulator solver should be able to handle it.

**Comment by samvanderzwan** [comment]
indeed so we could remove it

**Comment by samvanderzwan** [comment]
No, since we are no longer using pandapipes
