### ISSUE TITLE
Junction and Asset set initial temperature from ESDL carrier

### ISSUE THREAD

**Issue by vanmeerkerk** [Project-OMOTES/simulator-core#53]
@octavianor mentioned a convergence issue when the initial temperatures are too far from their expected values. 

@samvanderzwan @MichielTukker do we want to set the supply, return temp. of assets with the "add_physical_data" call? Maybe we should set this when we're connecting the junctions to the assets? That way we known the specific carrier of said junction. In addition, we can then add a add_physical_data call to the junctions?

**Comment by vanmeerkerk** [comment]
In asset create methods "set_from_junction(temp)" and "set_to_junction(temp)" to set the default temperatures.

**Comment by vanmeerkerk** [comment]
@samvanderzwan do we want to implement this on the new solver? I believe that this issue is only relevant for pandapipes?

**Comment by samvanderzwan** [comment]
I also think this is no longer relevant will close the issue
