### ISSUE TITLE
Discuss which assert to use for unit testing

### ISSUE THREAD

**Issue by samvanderzwan** [Project-OMOTES/simulator-core#59]
In writing unit test you can use the keyword assert or you can use self.assertEqual which to use. To be discussed with @MichielTukker and @TNO-SlaFleur

**Comment by TNO-SlaFleur** [comment]
assert is a Python specific keyword. self.assertEqual is a method given by the unit test framework. Advise is to use self.assertEqual as it forces type checking and it handles the 'typeness' better. With assert you have to give a boolean formula which may not handle the types of expected & result properly.

**Comment by samvanderzwan** [comment]
Please note if we do this this flake8 rule needs to be disabled: PT009: see https://github.com/m-burst/flake8-pytest-style/blob/master/docs/rules/PT009.md for explanation

**Comment by vanmeerkerk** [comment]
Reformat unit tests and verify that they all use self.assert
