### ISSUE TITLE
Profiling possibilities

### ISSUE THREAD

**Issue by samvanderzwan** [Project-OMOTES/simulator-core#68]
To check where we can increase speed, it would be could to add profiling tools.
CProfile module (https://docs.python.org/3/library/profile.html) werkt goed en dan https://jiffyclub.github.io/snakeviz/
voor visualisatie

**Comment by vanmeerkerk** [comment]
@samvanderzwan what do you want to do in this issue? Is this an additional ci/ module?

**Comment by samvanderzwan** [comment]
yes that is indeed the idea
