### ISSUE TITLE
Improve matrix class

### ISSUE THREAD

**Issue by samvanderzwan** [Project-OMOTES/simulator-core#77]

**Comment by vanmeerkerk** [comment]
@samvanderzwan  explain what you want to do?

**Comment by samvanderzwan** [comment]
TODO's for Matrix class

- [ ] Add sparse matrix solver
- [ ] Method get_solution: add checks if the index and number of unknowns are within the range of the solution.
- [ ] Method solve: add checks if enough equations have been supplied.
- [ ] Method solve: check if matrix is solvable.

**Comment by samvanderzwan** [comment]
Added the sparse matrix solver. Performed tests and comparison for attached model simulating 7 months 
[cluster2merged_pipes.esdl.txt](https://github.com/Project-OMOTES/simulator-core/files/15110478/cluster2merged_pipes.esdl.txt)
Reuslt where smaller then 1e-8.
Time is 3300 s for full matrix to 1300 s for sparse matrix solver

**Comment by samvanderzwan** [comment]
I have added check when the matrix is solved to check if the result is not a number. if this is the case then the matrix is singular. I did not add a routine to check whether the matrix becomes singular and where. This is for now to much work. I will make a separate issue out of that.
