### ISSUE TITLE
Switch from PandaPipes to own solver

### ISSUE THREAD

**Issue by MichielTukker** [Project-OMOTES/simulator-core#86]
During development,    @samvanderzwan  and @mvmeerkerk  have discovered multiple issues with PandaPipes where we are working around the limitations imposed by this external dependency.  The proposal is to switch from PandaPipes to an custom set of equations and matrix solver for the hydraulic & thermal computation. 

External reference to pandapipes issue (blocking issue): https://github.com/e2nIEE/pandapipes/issues/594

Additional explanation needed! @samvanderzwan @mvmeerkerk 

Please comment further: @samvanderzwan @mvmeerkerk @octavianor

**Comment by samvanderzwan** [comment]
This has been merged into the main and made available for the MVP so issue will be closed
