### ISSUE TITLE
split  EsdlEnergySystemMapper.to_entity into smaller part

### ISSUE THREAD

**Issue by samvanderzwan** [Project-OMOTES/simulator-core#92]
see https://github.com/Project-OMOTES/simulator-core/pull/91#issuecomment-1983811671
This method is to long and should be split into smaller parts. Also part of the code is repeated which is not nice.

**Comment by vanmeerkerk** [comment]
Is linked to #60 ; closed #60.

**Comment by AshrafAlmohagryDeltares** [comment]
This seems to have already been fixed.
